### ISSUE TITLE
Meaningfulness of minOccurs greater 0 in multiply blocks

### ISSUE THREAD

**Issue by rs2487** [sulu-cmf/sulu-standard#293]
I think we should set the minOccurs to 0 when multiply blocks not explizit needed in for correct visualization of the design.

**Comment by danrot** [comment]
IMHO it would make more sense to default to 1, I imagine it to be the more general usecase that one content block has to exist.

**Comment by wachterjohannes** [comment]
i agree with @danrot we should leave 1 as minimum count!

**Comment by danrot** [comment]
@chirimoya If this is also ok for you we could close this issue :-)

**Comment by wachterjohannes** [comment]
if you have no mandatory field in you block type you can say minOccurs 1 and you dont have to fill in the block fields ... this is discussed with @chirimoya and i close it
