### ISSUE TITLE
(Back) To Website Link in Sulu

### ISSUE THREAD

**Issue by rs2487** [sulu-cmf/sulu-standard#294]
Is it possible to add this links to Sulu. I often used it Zoolu:
http://cl.ly/image/0B1v0E1q2M1z (Zurück zur Website)
http://cl.ly/image/2S363y1R0p0I (Website öffnen)

**Comment by danrot** [comment]
@berndhep What do you think about this feature?

**Comment by berndhep** [comment]
@rs2487 @danrot I've added the link to the new login window (it will redirect to the top-level domain). Once you're logged-in, a similar link can't be placed because since we have a multi-platform CMS it wouldn't be clear which website should be opened.

**Comment by danrot** [comment]
Ok, I guess @marcelmoosbrugger can already start implementing this in this week then.
