### ISSUE TITLE
[peview] Cannot handle empty requests

### ISSUE THREAD

**Issue by dantleech** [sulu-cmf/sulu-standard#357]
In the following PR it was necessary to send additional data in the request payload in order for the preview to work.

https://github.com/sulu-cmf/SuluSnippetBundle/pull/13#discussion_r19393709

In this case we wanted to render a snippets content type with no snippets (and so no data at all). But this failed because the request payload evaluated as `NULL`.

**Comment by danrot** [comment]
I have removed your junk in https://github.com/sulu-cmf/sulu/pull/806 and the preview is also working when sending an empty array.
