### ISSUE TITLE
2 Titles for Browser Tab

### ISSUE THREAD

**Issue by katehepberger** [sulu-cmf/sulu-standard#361]
When you're reading the page it shows a different Tab title than when you change tab. You then get a "Don't forget to read" Info. Might be a nice feature. TBD (Kate & Stefanie) http://blog.invisionapp.com/inside-the-design-team-at-fjord/?utm_source=fjord&utm_medium=email&utm_campaign=designspaces

**Comment by danrot** [comment]
@katehepberger Isn't this only website specific? Or what support from Sulu do you expect here?

**Comment by katehepberger** [comment]
@danrot Yep that is Frontend, but would be nice if organized through the SULU Team. Not?

**Comment by danrot** [comment]
I don't really know what we should organize here... In case you want to do that you have to add a textfield to the template, and changing the title has also to be done in your template. These files are completely project-specific, and are not touched by us.

So this feature is already available in some way :-)
