### ISSUE TITLE
Content Repository property value type switch error

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-cmf/sulu-standard#377]
Some Template can have a field with same name but other content type or in development a field switch from one content type to another it can happen that the content type before was array and now is single value or vice versa. When this happens content repository will throw an error that the field is not from this type. To fix it you need to $node->getProperty('fieldname')->remove() before you can save the page with the new content type. Maybe we can catch the exception and automate remove process in this case?

**Comment by danrot** [comment]
@wachterjohannes Isn't that already solved?

**Comment by wachterjohannes** [comment]
Yeah i think @alexander-schranz has aded this delete before save new data to th property! schould i close it?

**Comment by danrot** [comment]
I can do that as well ;-)
