### ISSUE TITLE
Page titles in "" don't show in sulu navigation 

### ISSUE THREAD

**Issue by BettinaKaljo** [sulu-cmf/sulu-standard#380]

**Comment by danrot** [comment]
@wachterjohannes Is this still an issue?

**Comment by wachterjohannes** [comment]
i cannot reproduce it anymore ... but i will ask @BettinaKaljo for that issue!

**Comment by BettinaKaljo** [comment]
still existing. see the attaches screenshot: 
![bildschirmfoto 2015-02-13 um 14 18 25](https://cloud.githubusercontent.com/assets/2741493/6187800/66c974ae-b38b-11e4-92b2-99f16ac50762.png)
