### ISSUE TITLE
Smart content regards only first tag

### ISSUE THREAD

**Issue by BettinaKaljo** [sulu-cmf/sulu-standard#399]
Only the first tag is considered in smart content definitions although some tags can be defined.

**Comment by danrot** [comment]
Don't know yet, however, can you move that issue to sulu-cmf/sulu and link the issue in jackalope-doctrine-dbal?

**Comment by wachterjohannes** [comment]
new issue created here https://github.com/sulu-cmf/sulu/issues/787
