### ISSUE TITLE
Init database with correct encoding (utf8)

### ISSUE THREAD

**Issue by turbo-ele** [sulu-cmf/sulu-standard#41]
encoding should be utf8 not latin1_swedish_cl

**Comment by danrot** [comment]
Just checked my installation:
![image](https://cloud.githubusercontent.com/assets/405874/6176318/32b7b870-b2fe-11e4-8d29-5da61b4bbe3a.png)

Seems as if the database encoding is setup correctly, therefore I close this issue.
